version: "2.1"

services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "8086:8086"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db/
      SPRING_R2DBC_NAME: postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: password
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db/postgres
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: password
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:db/changelog/db.changelog-master.xml