version: "2.3"

services:
  database:
    image: postgres:13-alpine
    container_name: getman-db
    # ports:
    #   - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${PG_DB:?database name is required}
      - POSTGRES_USER=${PG_USER:?database user is required}
      - POSTGRES_PASSWORD=${PG_PASS:?database password is required}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build: .
    container_name: getman-backend
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    # ports:
    #   - 8086:8086
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://getman-db/
      SPRING_R2DBC_NAME: ${PG_DB}
      SPRING_R2DBC_USERNAME: ${PG_USER}
      SPRING_R2DBC_PASSWORD: ${PG_PASS}
      SPRING_LIQUIBASE_URL: jdbc:postgresql://getman-db/${PG_DB}
      SPRING_LIQUIBASE_USER: ${PG_USER}
      SPRING_LIQUIBASE_PASSWORD: ${PG_PASS}
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:db/changelog/db.changelog-master.xml

  webserver:
    image: nginx:latest
    container_name: getman-webserver
    links:
      - backend
    volumes:
      - ./nginx/templates:/etc/nginx/templates/
      - ./nginx/includes:/etc/nginx/includes/
      - ./data/certs:/var/certs/
      - ./data/app:/var/www/app/
    ports:
      - 9080:80
      - 9443:443
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      # DOMAIN: getman.local
      DOMAIN: localhost
      BACKEND_URI: http://getman-backend:8086
