name: getman_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  auto_route: ^6.0.0-rc-3
  code_text_field: ^1.1.0
  collection: ^1.17.1
  dart_mappable: ^3.0.0-dev.0
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^2.3.0
  highlight: ^0.7.0
  meta: ^1.9.0
  multi_split_view: ^2.4.0
  path: ^1.8.3
  pretty_dio_logger: ^1.3.1
  reactive_forms: ^14.2.0
  riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  uri: ^1.0.0

dev_dependencies:
  auto_route_generator: ^6.0.0-rc
  build_runner: ^2.4.0
  dart_mappable_builder: ^3.0.0-dev.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.0.0
  zekfad_lints: ^1.2.0

dependency_overrides:
  dart_mappable:
    git:
      url: https://github.com/schultek/dart_mappable.git
      path: packages/dart_mappable
  dart_mappable_builder:
    git:
      url: https://github.com/schultek/dart_mappable.git
      path: packages/dart_mappable_builder

flutter:
  uses-material-design: true
